usgsProperties:
  schema: "https://"
  host: "earthquake.usgs.gov"
  port: ""
  path: "/fdsnws/event/1"

usgsEndPoint:
  earthQuakesBetweenDate: "/query"
  earthQuakesCount: "/count"
  startTimeParam: "starttime"
  endTimeParam: "endtime"
  minMagnitudeParam: "minmagnitude"
  maxMagnitudeParam: "maxmagnitude"
  formatParam: "format"
  formatValue: "geojson"